name: Deploy para Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Verificar secrets
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ] || [ -z "${{ secrets.VERCEL_TEAM_ID }}" ] || [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "Erro: Algum secret da Vercel não está configurado."
            exit 1
          fi

      - name: Deploy na Vercel
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} \
                 --prod \
                 --confirm \
                 --scope ${{ secrets.VERCEL_TEAM_ID }} \
                 --project ${{ secrets.VERCEL_PROJECT_ID }}
